### ISSUE TITLE
s[pattern] substitution breaks highlighting

### ISSUE THREAD

**Issue by nottalulah** [Raku/atom-language#69]
> Describe what you see, what you want to see, and perhaps some linkage to docs, synopses, or irclog chatter.

The `s[pattern] = doit()` substitution /e modifier replacement defined in [S05](https://design.perl6.org/S05.html#Modifiers) breaks highlighting if used with adverbs. It also doesn't apply regex highlighting, even without adverbs.

### Example Code
```perl6
sub some-sub(Str $something) is export
{
	my $s = $something.subst("::", "");
	$s ~~ s:g[(<[A..Z]>)(<[A..Z]>*)] = $0 ~ lc($1);
	$s;
}
sub another-sub is export { return some-sub("Hello::World"); }
```
### Picture [optional]
![fvvrmey](https://cloud.githubusercontent.com/assets/26291500/26366288/e3c47d1e-3fc0-11e7-895b-5ec3f1434621.png)

### Leave this in. For internal use.
- [x] Fixed in Master
- [ ] Fixed in Release
- [x] Has Tests
- [x] Passes Tests

**Comment by samcv** [comment]
This is fixed now in master. Will be releasing once travis runs.
