### ISSUE TITLE
Merge/package with atom-perl6-editor-tools?

### ISSUE THREAD

**Issue by nxadm** [Raku/atom-language#85]
In order to have good Perl 6 support in atom, you'll need to enable this project and [atom-perl6-editor-tools](https://github.com/azawawi/atom-perl6-editor-tools). Specially the [Syntax Check Linter](https://github.com/azawawi/atom-perl6-editor-tools#syntax-check-linter) is something many people appreciate nowadays.

I don't know how realistic is for both projects to collaborate (ping @azawawi), but even a meta package providing both plugins would be a huge step forward (if there aren't conflicting features). I suspect people are confused about which plugin to pick.

**Comment by 2colours** [comment]
These projects have become severely outdated and have fallen out of scope for this repository.
