### ISSUE TITLE
Rename to atom-language-raku

### ISSUE THREAD

**Issue by hankache** [Raku/atom-language#91]
Update for Raku name change

**Comment by AlexDaniel** [comment]
Where does the name come from? Is it based on the github repo or something?

The repos will be moved to another github org soon. I'm expecting the process to start next week.

**Comment by hankache** [comment]
I am just posting this issue so that we remember to take care of the rename on this repo.

**Comment by 2colours** [comment]
The repo got moved and renamed - I'd hope for "Atom" to be completely outsourced in the long run but anyway, that sounds like a different issue.
